services:
        postgresdb:
                image: postgres:16.2-alpine3.19

                environment: 
                        POSTGRES_PASSWORD: password
                ports:
                        - 54321:5432
